export const SOCKET_EVENTS = {
  START_SESSION: "start_session",
  SEND_MESSAGE: "send_message",
  TYPING: "typing",
  JOIN_SESSION: "join_session",
  NEW_MESSAGE: "new_message",
  USER_CONNECTED: "user_connected",
  USER_DISCONNECTED: "user_disconnected",
  ADMIN_STATUS: "admin_status",
  UNREAD_COUNTS: "unread_counts",
  SCREEN_SHARE_OFFER: "screen_share_offer",
  SCREEN_SHARE_ANSWER: "screen_share_answer",
  SCREEN_SHARE_ICE: "screen_share_ice",
  SCREEN_SHARE_STOP: "screen_share_stop",
  SCREEN_SHARE_REQUEST: "screen_share_request",
  VOICE_CALL_OFFER: "voice_call_offer",
  VOICE_CALL_ANSWER: "voice_call_answer",
  VOICE_CALL_ICE: "voice_call_ice",
  VOICE_CALL_END: "voice_call_end",
  VOICE_CALL_REQUEST: "voice_call_request",
  VOICE_MUTE_STATE: "voice_mute_state",
  VOICE_REMOTE_MUTE: "voice_remote_mute",
};
